// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoTool.Api.Persistence;

#nullable disable

namespace PoTool.Api.Migrations
{
    [DbContext(typeof(PoToolDbContext))]
    [Migration("20260119144056_AddWorkItemStateClassifications")]
    partial class AddWorkItemStateClassifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.CachedValidationResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Indicator")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpicId")
                        .IsUnique();

                    b.ToTable("CachedValidationResults");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.EffortEstimationSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultEffortBug")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultEffortEpic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultEffortFeature")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultEffortGeneric")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultEffortPBI")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultEffortTask")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultEffortUserStory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableProactiveNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EffortEstimationSettings");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.EpicPlacementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderInRow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpicId")
                        .IsUnique();

                    b.HasIndex("LaneId", "RowIndex", "OrderInRow");

                    b.ToTable("EpicPlacements");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.IterationLineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("VerticalPosition")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("IterationLines");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.LaneEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectiveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveId")
                        .IsUnique();

                    b.ToTable("Lanes");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.MilestoneLineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VerticalPosition")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MilestoneLines");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.PipelineDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Folder")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSyncedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PipelineDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepoId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("YamlPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("ProductId", "PipelineDefinitionId")
                        .IsUnique();

                    b.ToTable("PipelineDefinitions");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacklogRootWorkItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomPicturePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PictureType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductOwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductOwnerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.ProductTeamLinkEntity", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("ProductTeamLinks");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.ProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomPicturePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoalIds")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PictureType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.PullRequestCommentEntity", b =>
                {
                    b.Property<int>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("PullRequestId");

                    b.HasIndex("ThreadId");

                    b.ToTable("PullRequestComments");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.PullRequestEntity", b =>
                {
                    b.Property<int>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IterationPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IterationPath");

                    b.HasIndex("ProductId");

                    b.HasIndex("RepositoryName");

                    b.HasIndex("Status");

                    b.ToTable("PullRequests");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.PullRequestFileChangeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("IterationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinesDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinesModified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId", "IterationId");

                    b.ToTable("PullRequestFileChanges");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.PullRequestIterationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommitCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IterationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId", "IterationNumber")
                        .IsUnique();

                    b.ToTable("PullRequestIterations");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.RepositoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.SettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.SprintEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSyncedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TfsIterationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeFrame")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "Path")
                        .IsUnique();

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomPicturePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedIterationsUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PictureType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamAreaPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TfsTeamId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TfsTeamName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.TfsConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultAreaPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasTestedConnectionSuccessfully")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasVerifiedTfsApiSuccessfully")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastValidated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseDefaultCredentials")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Url");

                    b.ToTable("TfsConfigs");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.WorkItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Effort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IterationPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTfsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TfsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TfsId")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.HasIndex("Type");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.WorkItemStateClassificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TfsProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkItemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TfsProjectName", "WorkItemType", "StateName")
                        .IsUnique();

                    b.ToTable("WorkItemStateClassifications");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.EpicPlacementEntity", b =>
                {
                    b.HasOne("PoTool.Api.Persistence.Entities.LaneEntity", "Lane")
                        .WithMany("Placements")
                        .HasForeignKey("LaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lane");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.PipelineDefinitionEntity", b =>
                {
                    b.HasOne("PoTool.Api.Persistence.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoTool.Api.Persistence.Entities.RepositoryEntity", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.ProductEntity", b =>
                {
                    b.HasOne("PoTool.Api.Persistence.Entities.ProfileEntity", "ProductOwner")
                        .WithMany("Products")
                        .HasForeignKey("ProductOwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProductOwner");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.ProductTeamLinkEntity", b =>
                {
                    b.HasOne("PoTool.Api.Persistence.Entities.ProductEntity", "Product")
                        .WithMany("ProductTeamLinks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoTool.Api.Persistence.Entities.TeamEntity", "Team")
                        .WithMany("ProductTeamLinks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.PullRequestEntity", b =>
                {
                    b.HasOne("PoTool.Api.Persistence.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.RepositoryEntity", b =>
                {
                    b.HasOne("PoTool.Api.Persistence.Entities.ProductEntity", "Product")
                        .WithMany("Repositories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.SprintEntity", b =>
                {
                    b.HasOne("PoTool.Api.Persistence.Entities.TeamEntity", "Team")
                        .WithMany("Sprints")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.LaneEntity", b =>
                {
                    b.Navigation("Placements");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.ProductEntity", b =>
                {
                    b.Navigation("ProductTeamLinks");

                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.ProfileEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PoTool.Api.Persistence.Entities.TeamEntity", b =>
                {
                    b.Navigation("ProductTeamLinks");

                    b.Navigation("Sprints");
                });
#pragma warning restore 612, 618
        }
    }
}
