using PoTool.Shared.DataState;
using PoTool.Shared.Health;
using PoTool.Shared.Metrics;
using PoTool.Shared.Pipelines;
using PoTool.Shared.PullRequests;
using PoTool.Shared.Planning;
using PoTool.Shared.BuildQuality;
using PoTool.Shared.WorkItems;
using PoTool.Shared.ReleasePlanning;
using PoTool.Shared.Statistics;

namespace PoTool.Client.ApiClient;

public interface IGeneratedDataStateEnvelope<out TData>
{
    DataStateDto State { get; }
    TData? Data { get; }
    string? Reason { get; }
    int? RetryAfterSeconds { get; }
}

public partial class DataStateResponseDtoOfDeliveryQueryResponseDtoOfBuildQualityPageDto : IGeneratedDataStateEnvelope<DeliveryQueryResponseDtoOfBuildQualityPageDto>;
public partial class DataStateResponseDtoOfDeliveryQueryResponseDtoOfDeliveryBuildQualityDto : IGeneratedDataStateEnvelope<DeliveryQueryResponseDtoOfDeliveryBuildQualityDto>;
public partial class DataStateResponseDtoOfPipelineBuildQualityDto : IGeneratedDataStateEnvelope<PipelineBuildQualityDto>;
public partial class DataStateResponseDtoOfProjectPlanningSummaryDto : IGeneratedDataStateEnvelope<ProjectPlanningSummaryDto>;
public partial class DataStateResponseDtoOfSprintQueryResponseDtoOfSprintMetricsDto : IGeneratedDataStateEnvelope<SprintQueryResponseDtoOfSprintMetricsDto>;
public partial class DataStateResponseDtoOfSprintQueryResponseDtoOfBacklogHealthDto : IGeneratedDataStateEnvelope<SprintQueryResponseDtoOfBacklogHealthDto>;
public partial class DataStateResponseDtoOfSprintQueryResponseDtoOfMultiIterationBacklogHealthDto : IGeneratedDataStateEnvelope<SprintQueryResponseDtoOfMultiIterationBacklogHealthDto>;
public partial class DataStateResponseDtoOfEffortDistributionDto : IGeneratedDataStateEnvelope<EffortDistributionDto>;
public partial class DataStateResponseDtoOfEpicCompletionForecastDto : IGeneratedDataStateEnvelope<EpicCompletionForecastDto>;
public partial class DataStateResponseDtoOfSprintQueryResponseDtoOfSprintCapacityPlanDto : IGeneratedDataStateEnvelope<SprintQueryResponseDtoOfSprintCapacityPlanDto>;
public partial class DataStateResponseDtoOfDeliveryQueryResponseDtoOfCapacityCalibrationDto : IGeneratedDataStateEnvelope<DeliveryQueryResponseDtoOfCapacityCalibrationDto>;
public partial class DataStateResponseDtoOfDeliveryQueryResponseDtoOfPortfolioDeliveryDto : IGeneratedDataStateEnvelope<DeliveryQueryResponseDtoOfPortfolioDeliveryDto>;
public partial class DataStateResponseDtoOfSprintQueryResponseDtoOfGetSprintTrendMetricsResponse : IGeneratedDataStateEnvelope<SprintQueryResponseDtoOfGetSprintTrendMetricsResponse>;
public partial class DataStateResponseDtoOfDeliveryQueryResponseDtoOfPortfolioProgressTrendDto : IGeneratedDataStateEnvelope<DeliveryQueryResponseDtoOfPortfolioProgressTrendDto>;
public partial class DataStateResponseDtoOfDeliveryQueryResponseDtoOfHomeProductBarMetricsDto : IGeneratedDataStateEnvelope<DeliveryQueryResponseDtoOfHomeProductBarMetricsDto>;
public partial class DataStateResponseDtoOfSprintQueryResponseDtoOfSprintExecutionDto : IGeneratedDataStateEnvelope<SprintQueryResponseDtoOfSprintExecutionDto>;
public partial class DataStateResponseDtoOfSprintQueryResponseDtoOfWorkItemActivityDetailsDto : IGeneratedDataStateEnvelope<SprintQueryResponseDtoOfWorkItemActivityDetailsDto>;
public partial class DataStateResponseDtoOfPortfolioProgressDto : IGeneratedDataStateEnvelope<PortfolioProgressDto>;
public partial class DataStateResponseDtoOfPortfolioSnapshotDto : IGeneratedDataStateEnvelope<PortfolioSnapshotDto>;
public partial class DataStateResponseDtoOfPortfolioComparisonDto : IGeneratedDataStateEnvelope<PortfolioComparisonDto>;
public partial class DataStateResponseDtoOfPortfolioTrendDto : IGeneratedDataStateEnvelope<PortfolioTrendDto>;
public partial class DataStateResponseDtoOfPortfolioSignalsDto : IGeneratedDataStateEnvelope<PortfolioSignalsDto>;
public partial class DataStateResponseDtoOfPipelineQueryResponseDtoOfIReadOnlyListOfPipelineMetricsDto : IGeneratedDataStateEnvelope<PipelineQueryResponseDtoOfIReadOnlyListOfPipelineMetricsDto>;
public partial class DataStateResponseDtoOfPipelineQueryResponseDtoOfIReadOnlyListOfPipelineRunDto : IGeneratedDataStateEnvelope<PipelineQueryResponseDtoOfIReadOnlyListOfPipelineRunDto>;
public partial class DataStateResponseDtoOfPipelineQueryResponseDtoOfPipelineInsightsDto : IGeneratedDataStateEnvelope<PipelineQueryResponseDtoOfPipelineInsightsDto>;
public partial class DataStateResponseDtoOfIEnumerableOfPipelineDto : IGeneratedDataStateEnvelope<ICollection<PipelineDto>>;
public partial class DataStateResponseDtoOfIEnumerableOfPipelineRunDto : IGeneratedDataStateEnvelope<ICollection<PipelineRunDto>>;
public partial class DataStateResponseDtoOfIEnumerableOfPullRequestDto : IGeneratedDataStateEnvelope<ICollection<PullRequestDto>>;
public partial class DataStateResponseDtoOfPullRequestDto : IGeneratedDataStateEnvelope<PullRequestDto>;
public partial class DataStateResponseDtoOfIEnumerableOfPullRequestCommentDto : IGeneratedDataStateEnvelope<ICollection<PullRequestCommentDto>>;
public partial class DataStateResponseDtoOfIEnumerableOfPullRequestIterationDto : IGeneratedDataStateEnvelope<ICollection<PullRequestIterationDto>>;
public partial class DataStateResponseDtoOfPullRequestQueryResponseDtoOfIReadOnlyListOfPullRequestMetricsDto : IGeneratedDataStateEnvelope<PullRequestQueryResponseDtoOfIReadOnlyListOfPullRequestMetricsDto>;
public partial class DataStateResponseDtoOfPullRequestQueryResponseDtoOfIReadOnlyListOfPullRequestDto : IGeneratedDataStateEnvelope<PullRequestQueryResponseDtoOfIReadOnlyListOfPullRequestDto>;
public partial class DataStateResponseDtoOfPullRequestQueryResponseDtoOfGetPrSprintTrendsResponse : IGeneratedDataStateEnvelope<PullRequestQueryResponseDtoOfGetPrSprintTrendsResponse>;
public partial class DataStateResponseDtoOfPullRequestQueryResponseDtoOfPullRequestInsightsDto : IGeneratedDataStateEnvelope<PullRequestQueryResponseDtoOfPullRequestInsightsDto>;
public partial class DataStateResponseDtoOfPullRequestQueryResponseDtoOfPrDeliveryInsightsDto : IGeneratedDataStateEnvelope<PullRequestQueryResponseDtoOfPrDeliveryInsightsDto>;
public partial class DataStateResponseDtoOfReleasePlanningBoardDto : IGeneratedDataStateEnvelope<ReleasePlanningBoardDto>;
public partial class DataStateResponseDtoOfIReadOnlyListOfUnplannedEpicDto : IGeneratedDataStateEnvelope<ICollection<UnplannedEpicDto>>;
public partial class DataStateResponseDtoOfIReadOnlyListOfObjectiveEpicDto : IGeneratedDataStateEnvelope<ICollection<ObjectiveEpicDto>>;
public partial class DataStateResponseDtoOfLaneOperationResultDto : IGeneratedDataStateEnvelope<LaneOperationResultDto>;
public partial class DataStateResponseDtoOfEpicPlacementResultDto : IGeneratedDataStateEnvelope<EpicPlacementResultDto>;
public partial class DataStateResponseDtoOfLineOperationResultDto : IGeneratedDataStateEnvelope<LineOperationResultDto>;
public partial class DataStateResponseDtoOfValidationCacheResultDto : IGeneratedDataStateEnvelope<ValidationCacheResultDto>;
public partial class DataStateResponseDtoOfExportResultDto : IGeneratedDataStateEnvelope<ExportResultDto>;
public partial class DataStateResponseDtoOfIReadOnlyListOfEpicFeatureDto : IGeneratedDataStateEnvelope<ICollection<EpicFeatureDto>>;
public partial class DataStateResponseDtoOfEpicSplitResultDto : IGeneratedDataStateEnvelope<EpicSplitResultDto>;
public partial class DataStateResponseDtoOfIEnumerableOfWorkItemDto : IGeneratedDataStateEnvelope<ICollection<WorkItemDto>>;
public partial class DataStateResponseDtoOfWorkItemWithValidationDto : IGeneratedDataStateEnvelope<WorkItemWithValidationDto>;
public partial class DataStateResponseDtoOfIEnumerableOfWorkItemWithValidationDto : IGeneratedDataStateEnvelope<ICollection<WorkItemWithValidationDto>>;
public partial class DataStateResponseDtoOfValidationTriageSummaryDto : IGeneratedDataStateEnvelope<ValidationTriageSummaryDto>;
public partial class DataStateResponseDtoOfHealthWorkspaceProductSummaryDto : IGeneratedDataStateEnvelope<HealthWorkspaceProductSummaryDto>;
public partial class DataStateResponseDtoOfValidationQueueDto : IGeneratedDataStateEnvelope<ValidationQueueDto>;
public partial class DataStateResponseDtoOfValidationFixSessionDto : IGeneratedDataStateEnvelope<ValidationFixSessionDto>;
public partial class DataStateResponseDtoOfIEnumerableOfWorkItemRevisionDto : IGeneratedDataStateEnvelope<ICollection<WorkItemRevisionDto>>;
public partial class DataStateResponseDtoOfDependencyGraphDto : IGeneratedDataStateEnvelope<DependencyGraphDto>;
public partial class DataStateResponseDtoOfProductBacklogStateDto : IGeneratedDataStateEnvelope<ProductBacklogStateDto>;
public partial class DataStateResponseDtoOfFilterByValidationResponse : IGeneratedDataStateEnvelope<FilterByValidationResponse>;
public partial class DataStateResponseDtoOfGetWorkItemIdsByValidationFilterResponse : IGeneratedDataStateEnvelope<GetWorkItemIdsByValidationFilterResponse>;
public partial class DataStateResponseDtoOfCountWorkItemsByValidationFilterResponse : IGeneratedDataStateEnvelope<CountWorkItemsByValidationFilterResponse>;
public partial class DataStateResponseDtoOfIsDescendantOfGoalsResponse : IGeneratedDataStateEnvelope<IsDescendantOfGoalsResponse>;
public partial class DataStateResponseDtoOfFilterByGoalsResponse : IGeneratedDataStateEnvelope<FilterByGoalsResponse>;
public partial class DataStateResponseDtoOfWorkItemStateTimelineDto : IGeneratedDataStateEnvelope<WorkItemStateTimelineDto>;
public partial class DataStateResponseDtoOfIEnumerableOfValidationViolationHistoryDto : IGeneratedDataStateEnvelope<ICollection<ValidationViolationHistoryDto>>;
public partial class DataStateResponseDtoOfValidationImpactAnalysisDto : IGeneratedDataStateEnvelope<ValidationImpactAnalysisDto>;
