using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace PoTool.Client.Services;

/// <summary>
/// Service for generating roadmap reports, structured exports, and AI prompt templates.
/// Read-only — never modifies TFS data. Uses the same filtering and ordering rules
/// as the Product Roadmaps overview page.
/// </summary>
public class RoadmapReportingService
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    /// <summary>
    /// Generates a structured roadmap report from product lane data.
    /// </summary>
    /// <param name="lanes">Product lanes with roadmap epics, already filtered and ordered.</param>
    /// <returns>A structured roadmap report.</returns>
    public RoadmapReport GenerateReport(IReadOnlyList<RoadmapProductEntry> lanes)
    {
        ArgumentNullException.ThrowIfNull(lanes);

        return new RoadmapReport
        {
            GeneratedAtUtc = DateTimeOffset.UtcNow,
            TotalProducts = lanes.Count,
            TotalEpics = lanes.Sum(l => l.Epics.Count),
            Products = lanes
        };
    }

    /// <summary>
    /// Exports the roadmap as structured JSON suitable for AI or external tools.
    /// </summary>
    /// <param name="lanes">Product lanes with roadmap epics, already filtered and ordered.</param>
    /// <returns>A JSON string with the structured roadmap data.</returns>
    public string ExportStructuredJson(IReadOnlyList<RoadmapProductEntry> lanes)
    {
        var report = GenerateReport(lanes);
        return JsonSerializer.Serialize(report, JsonOptions);
    }

    /// <summary>
    /// Generates a presentation-friendly visual roadmap in Markdown.
    /// Shows product lanes horizontally with epics vertically.
    /// </summary>
    /// <param name="lanes">Product lanes with roadmap epics, already filtered and ordered.</param>
    /// <returns>A Markdown string with the visual roadmap layout.</returns>
    public string GenerateVisualRoadmap(IReadOnlyList<RoadmapProductEntry> lanes)
    {
        ArgumentNullException.ThrowIfNull(lanes);

        var sb = new StringBuilder();

        sb.AppendLine("# Product Roadmap Overview");
        sb.AppendLine();
        sb.AppendLine($"**Generated:** {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine($"**Products:** {lanes.Count}");
        sb.AppendLine($"**Total Roadmap Epics:** {lanes.Sum(l => l.Epics.Count)}");
        sb.AppendLine();

        if (lanes.Count == 0)
        {
            sb.AppendLine("_No products with roadmap epics found._");
            return sb.ToString();
        }

        // Summary table
        sb.AppendLine("## Portfolio Summary");
        sb.AppendLine();
        sb.AppendLine("| # | Product | Roadmap Epics |");
        sb.AppendLine("|---|---------|---------------|");

        for (var i = 0; i < lanes.Count; i++)
        {
            var lane = lanes[i];
            sb.AppendLine($"| {i + 1} | {EscapeMarkdown(lane.ProductName)} | {lane.Epics.Count} |");
        }

        sb.AppendLine();

        // Detail per product
        foreach (var lane in lanes)
        {
            sb.AppendLine($"## {EscapeMarkdown(lane.ProductName)}");
            sb.AppendLine();

            if (lane.Epics.Count == 0)
            {
                sb.AppendLine("_No roadmap epics._");
                sb.AppendLine();
                continue;
            }

            sb.AppendLine("| Order | Epic | TFS ID |");
            sb.AppendLine("|-------|------|--------|");

            foreach (var epic in lane.Epics)
            {
                sb.AppendLine($"| #{epic.Order} | {EscapeMarkdown(epic.Title)} | {epic.TfsId} |");
            }

            sb.AppendLine();
        }

        sb.AppendLine("---");
        sb.AppendLine("*Generated by PO Companion — Roadmap Reporting*");

        return sb.ToString();
    }

    /// <summary>
    /// Generates an AI prompt that embeds roadmap data for AI-assisted visualization.
    /// </summary>
    /// <param name="lanes">Product lanes with roadmap epics, already filtered and ordered.</param>
    /// <param name="template">The prompt template to use.</param>
    /// <returns>A prompt string with embedded roadmap data.</returns>
    public string GenerateAiPrompt(IReadOnlyList<RoadmapProductEntry> lanes, RoadmapPromptTemplate template)
    {
        ArgumentNullException.ThrowIfNull(lanes);

        var dataBlock = BuildRoadmapDataBlock(lanes);

        return template switch
        {
            RoadmapPromptTemplate.ExecutiveRoadmap => BuildExecutivePrompt(dataBlock),
            RoadmapPromptTemplate.CustomerFacingRoadmap => BuildCustomerFacingPrompt(dataBlock),
            RoadmapPromptTemplate.MilestoneInfographic => BuildMilestoneInfographicPrompt(dataBlock),
            _ => throw new ArgumentOutOfRangeException(nameof(template), template, "Unknown prompt template.")
        };
    }

    /// <summary>
    /// Returns the available prompt template options with descriptions.
    /// </summary>
    public static IReadOnlyList<PromptTemplateOption> GetAvailableTemplates() =>
    [
        new("Executive Roadmap", RoadmapPromptTemplate.ExecutiveRoadmap,
            "High-level strategic roadmap suitable for executive presentations."),
        new("Customer-Facing Roadmap", RoadmapPromptTemplate.CustomerFacingRoadmap,
            "Clean, outcome-focused roadmap suitable for external communication."),
        new("Milestone Infographic", RoadmapPromptTemplate.MilestoneInfographic,
            "Visual milestone-based infographic with numbered progression.")
    ];

    private static string BuildRoadmapDataBlock(IReadOnlyList<RoadmapProductEntry> lanes)
    {
        var sb = new StringBuilder();
        foreach (var lane in lanes)
        {
            sb.AppendLine($"Product: {lane.ProductName}");
            if (lane.Epics.Count == 0)
            {
                sb.AppendLine("  (no roadmap epics)");
            }
            else
            {
                foreach (var epic in lane.Epics)
                {
                    sb.AppendLine($"  {epic.Order}. {epic.Title} [TFS {epic.TfsId}]");
                }
            }

            sb.AppendLine();
        }

        return sb.ToString().TrimEnd();
    }

    private static string BuildExecutivePrompt(string dataBlock) =>
        $"""
         Create an executive-level product roadmap visualization based on the following structured data.

         Requirements:
         - Use a clean, professional layout suitable for board-level presentations.
         - Show each product as a horizontal lane.
         - Within each lane, display roadmap epics in their numbered order.
         - Use clear typography and minimal color to emphasize priority order.
         - Do not include technical details such as TFS IDs.
         - Add a title: "Product Roadmap — Executive Overview".

         Roadmap Data:
         {dataBlock}
         """;

    private static string BuildCustomerFacingPrompt(string dataBlock) =>
        $"""
         Create a customer-facing product roadmap visualization based on the following structured data.

         Requirements:
         - Use friendly, outcome-oriented language.
         - Show each product as a distinct section.
         - Within each section, list planned improvements in priority order.
         - Avoid internal terminology, technical IDs, and implementation details.
         - Use a warm, approachable visual style suitable for public communication.
         - Add a title: "What's Coming Next".

         Roadmap Data:
         {dataBlock}
         """;

    private static string BuildMilestoneInfographicPrompt(string dataBlock) =>
        $"""
         Create a milestone-based infographic roadmap based on the following structured data.

         Requirements:
         - Arrange products and their epics as a series of numbered milestones.
         - Each milestone corresponds to an epic in its priority order within a product.
         - Use a vertical or horizontal timeline layout with clear progression.
         - Include epic titles as milestone labels.
         - Group milestones by product using distinct visual sections.
         - Add a title: "Roadmap Milestones".

         Roadmap Data:
         {dataBlock}
         """;

    private static string EscapeMarkdown(string? text)
    {
        if (string.IsNullOrEmpty(text))
            return string.Empty;

        return text.Replace("|", "\\|")
                   .Replace("\n", " ")
                   .Replace("\r", string.Empty);
    }
}

/// <summary>
/// A complete roadmap report containing all products and their roadmap epics.
/// </summary>
public sealed record RoadmapReport
{
    public DateTimeOffset GeneratedAtUtc { get; init; }
    public int TotalProducts { get; init; }
    public int TotalEpics { get; init; }
    public IReadOnlyList<RoadmapProductEntry> Products { get; init; } = [];
}

/// <summary>
/// A single product entry in a roadmap report.
/// </summary>
public sealed record RoadmapProductEntry
{
    public string ProductName { get; init; } = string.Empty;
    public IReadOnlyList<RoadmapEpicEntry> Epics { get; init; } = [];
}

/// <summary>
/// A single epic entry in a roadmap report.
/// </summary>
public sealed record RoadmapEpicEntry
{
    public int Order { get; init; }
    public string Title { get; init; } = string.Empty;
    public int TfsId { get; init; }
}

/// <summary>
/// Available AI prompt templates for roadmap visualization.
/// </summary>
public enum RoadmapPromptTemplate
{
    ExecutiveRoadmap,
    CustomerFacingRoadmap,
    MilestoneInfographic
}

/// <summary>
/// Describes an available prompt template option for UI display.
/// </summary>
public sealed record PromptTemplateOption(string Name, RoadmapPromptTemplate Template, string Description);
